### ISSUE TITLE
SCH doesn't open on EagleCAD (or online SCH viewers)

### ISSUE THREAD

**Issue by petertorelli** [adafruit/4-Channel-Level-Shifter-PCB#2]
I tried opening the BRD file in EagleCAD and it worked fine, but clicking to SCH annotation it fails with this error:

~~~
EAGLE update report

Date: 10/16/20 12:27 PM
File: /Users/ptorelli/proj/git/4-Channel-Level-Shifter-PCB/Adafruit FET 4-Channel Shifter.sch

An error occurred while parsing the intermediate XML file.
The XML file has been loaded into a text editor window as
/Users/ptorelli/proj/git/4-Channel-Level-Shifter-PCB/Adafruit FET 4-Channel Shifter.rpt.sch

Error:

line 65, column 34: Unexpected ''.
~~~

Online viewers also fail to read the SCH (like schematics.io).

Also, the BRD file is text and the SCH is binary, seems odd. Even weirder, it did load in EagleCAD -once- and I have a screenshot, but now it will no longer open.

**Comment by jgarci25** [comment]
Its 2022 now and this issue has not been corrected... any advice?

**Comment by ladyada** [comment]
plz see 
https://learn.adafruit.com/accessing-and-using-adafruit-pcb-design-files?view=all

**Comment by petertorelli** [comment]
@ladyada 

This doesn't solve my problem. The .sch in this repo is unreadable by my EagleCad (version 9.3.2 and 9.6.2). Can you successfully open this .SCH, or is it just my setup and @jgarci25's?

**Comment by ladyada** [comment]
yep works fine for us in 9.6.2

**Comment by cscashby** [comment]
Newly downloaded 9.6.2 on Mac and line 65 causes errors. Tried downloading RAW from github, but also cloning direct to the mac. Seems like an encoding problem, but definitely there is an issue with this file.

**Comment by ladyada** [comment]
cant repro, just downloaded the zip and it opened directly in 9.6.2
